import { Layout } from '@/components/ui/layout/Layout'

export function App() {
  return (
    <Layout>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>
      <div>s</div>d
    </Layout>
  )
}
